version: "3"
services:
  web:
    build: .
    ports:
      - "{PORT}:{PORT}"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "redis"
    restart: always
