version: "3"
services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always
